angular.module('ExampleApp', ['angular-cron-gen', 'pascalprecht.translate'])
    .config(['$translateProvider', function ($translateProvider) {
		// add translation table
        $translateProvider.translations('en', {
            "cron": {
                "minutes": "Minutes",
                "hourly": "Hourly",
                "daily": "Daily",
                "weekly": "Weekly",
                "monthly": "Monthly",
                "yearly": "Yearly",
                "advanced": "Advanced",
                "every": "Every",
                "minute-s": "minutes(s)",
                "on-second": "on second",
                "hour-s-on-minute": "hour(s) on minute",
                "and-second": "and second",
                "day-s-at": "day(s) at",
                "every-week-day-monday-friday-at": "Every week day (Monday through Friday) at",
                "monday": "Monday",
                "tuesday": "Tuesday",
                "wednesday": "Wednesday",
                "thursday": "Thursday",
                "friday": "Friday",
                "saturday": "Saturday",
                "sunday": "Sunday",
                "start-time": "Start time",
                "on-the": "On the",
                "of-every": "of every",
                "month-s-at": "month(s) at",
                "at": "at",
                "of": "of",
                "cron-expression": "Cron Expression",
                "more-details": "More details about how to create these expressions can be found",
                "here": "here",
                "1W": "First Weekday",
                "1": "1st Day",
                "2": "2nd Day",
                "3": "3rd Day",
                "4": "4th Day",
                "5": "5th Day",
                "6": "6th Day",
                "7": "7th Day",
                "8": "8th Day",
                "9": "9th Day",
                "10": "10th Day",
                "11": "11th Day",
                "12": "12th Day",
                "13": "13th Day",
                "14": "14th Day",
                "15": "15th Day",
                "16": "16th Day",
                "17": "17th Day",
                "18": "18th Day",
                "19": "19th Day",
                "20": "20th Day",
                "21": "21st Day",
                "22": "22nd Day",
                "23": "23rd Day",
                "24": "24th Day",
                "25": "25th Day",
                "26": "26th Day",
                "27": "27th Day",
                "28": "28th Day",
                "29": "29th Day",
                "30": "30th Day",
                "31": "31st Day",
                "LW": "Last Weekday",
                "L": "Last Day",
                "month_1": "January",
                "month_2": "February",
                "month_3": "March",
                "month_4": "April",
                "month_5": "May",
                "month_6": "June",
                "month_7": "July",
                "month_8": "August",
                "month_9": "September",
                "month_10": "October",
                "month_11": "November",
                "month_12": "December",
                "SUN": "Sunday",
                "MON": "Monday",
                "TUE": "Tuesday",
                "WED": "Wednesday",
                "THU": "Thursday",
                "FRI": "Friday",
                "SAT": "Saturday",
                "monthDay#1": "First",
                "monthDay#2": "Second",
                "monthDay#3": "Third",
                "monthDay#4": "Fourth",
                "monthDay#5": "Fifth",
                "monthDayL": "Last"
            }
        });
        $translateProvider.translations('ro', {
            "cron": {
                "minutes": "Minute",
                "hourly": "În fiecare ora",
                "daily": "Zilnic",
                "weekly": "Săptămânal",
                "monthly": "Lunar",
                "yearly": "Anual",
                "advanced": "Avansat",
                "every": "La fiecare",
                "minute-s": "minut(e)",
                "on-second": "în secunda",
                "hour-s-on-minute": "oră(e) la minutul",
                "and-second": "și secunda",
                "day-s-at": "zi(zile) la",
                "every-week-day-monday-friday-at": "În fiecare zi a săptămânii (Luni - Vineri) la",
                "monday": "Luni",
                "tuesday": "Marți",
                "wednesday": "Miercuri",
                "thursday": "Joi",
                "friday": "Fineri",
                "saturday": "Sâmbătă",
                "sunday": "Duminica",
                "start-time": "Pornește la ora",
                "on-the": "În",
                "of-every": "din fiecare",
                "month-s-at": "lună(i) la",
                "at": "la",
                "of": "a lui",
                "cron-expression": "Expresie Programator",
                "more-details": "Mai multe detalii despre cum să creezi aceste expresii pot fi găsite",
                "here": "aici",
                "1W": "Prima zi a săptămânii",
                "1": "Prima zi",
                "2": "A 2-a zi",
                "3": "A 3-a zi",
                "4": "A 4-a zi",
                "5": "A 5-a zi",
                "6": "A 6-a zi",
                "7": "A 7-a zi",
                "8": "A 8-a zi",
                "9": "A 9-a zi",
                "10": "A 10-a zi",
                "11": "A 11-a zi",
                "12": "A 12-a zi",
                "13": "A 13-a zi",
                "14": "A 14-a zi",
                "15": "A 15-a zi",
                "16": "A 16-a zi",
                "17": "A 17-a zi",
                "18": "A 18-a zi",
                "19": "A 19-a zi",
                "20": "A 20-a zi",
                "21": "A 21-a zi",
                "22": "A 22-a zi",
                "23": "A 23-a zi",
                "24": "A 24-a zi",
                "25": "A 25-a zi",
                "26": "A 26-a zi",
                "27": "A 27-a zi",
                "28": "A 28-a zi",
                "29": "A 29-a zi",
                "30": "A 30-a zi",
                "31": "A 31-a zi",
                "LW": "Ultima zi a săptămânii",
                "L": "Ultima zi",
                "month_1": "Ianuarie",
                "month_2": "Februarie",
                "month_3": "Martie",
                "month_4": "Aprilie",
                "month_5": "Mai",
                "month_6": "Iunie",
                "month_7": "Iulie",
                "month_8": "August",
                "month_9": "Septembrir",
                "month_10": "Octombrie",
                "month_11": "Noiembrie",
                "month_12": "Decembrie",
                "SUN": "Duminică",
                "MON": "Luni",
                "TUE": "Marți",
                "WED": "Miercuri",
                "THU": "Joi",
                "FRI": "Vineri",
                "SAT": "Sâmbătă",
                "monthDay#1": "Prima",
                "monthDay#2": "A doua",
                "monthDay#3": "A treia",
                "monthDay#4": "A patra",
                "monthDay#5": "A cincea",
                "monthDayL": "Ultima"
            }
        });
        $translateProvider.preferredLanguage('en');
    }])
    .controller('ExampleCtrl', ['$scope', '$translate', function ($scope, $translate) {
        $scope.cronExpression = '0 15 9 9 1/8 ? *';
        $scope.currentLanguage = 'en';
        $scope.cronOptions = {
            hideAdvancedTab: false,
            stepMinutes: 5
        };
        $scope.isCronDisabled = false;

        // console.log('translate', $translate.use('ro'))

        $scope.changeLang = function (key) {
            $scope.currentLanguage = key;
            $translate.use($scope.currentLanguage);
        }
    }]);
